server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index 404.html;

    error_page 404 /404.html;

    location / {
        try_files $uri /404.html;
    }

    location ~* \.(html)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}